### ISSUE TITLE
add support with Sandstorm[Feature]

### ISSUE THREAD

**Issue by EthanJJC** [Vazkii/Ambience#13]
I used both Dynamic Surroundings and your Ambience 
But i can't let the Sandstorm like the rain
Wish you can do sth to support it~

**Comment by Vazkii** [comment]
I have no idea what you're talking about. Ambience fully supports DUDUDUDUDUDUDUDUDUDUDUDUDUDUDUDUDUDU.

**Comment by Vazkii** [comment]
Anyway, jokes aside. Crossmod integration should be on the other mod's end, using the API event.

**Comment by EthanJJC** [comment]
: p
