### ISSUE TITLE
it's me again(The real trouble)

### ISSUE THREAD

**Issue by EthanJJC** [Vazkii/Ambience#14]
You said that about Generic Song must be have this in your config or you risk a crash
If I want to play the customNPC's music in town but I can not stop the Generic Song 
So only I can do is made the Generic Song is empty?

**Comment by Vazkii** [comment]
Town event plays when you have villagers nearby.

**Comment by EthanJJC** [comment]
yes 
my design is the different town different music~ you know that
so i need use customNPC to play sounds 
The Generic Song can be stop?

**Comment by Vazkii** [comment]
Only by lowering the actual game music.

**Comment by EthanJJC** [comment]
will ~THX
