### ISSUE TITLE
Any chance for a 1.11 update?

### ISSUE THREAD

**Issue by xJon** [Vazkii/Ambience#24]
Thank you!

**Comment by liam4** [comment]
Indeed! The mod has been updated to 1.11 as of #26 ([this January](https://github.com/Vazkii/Ambience/commit/efe841d27cd94e9ea30ae2146fd18a09ffa5cb22)).

**Comment by xJon** [comment]
That's great! By the way, why did it change its ID?

**Comment by liam4** [comment]
[Apparently,](https://www.reddit.com/r/feedthebeast/comments/5hgu7l/psa_forge_mod_id_restrictions_are_now_being/) Forge now enforces lowercase mod IDs.
