### ISSUE TITLE
Fails to make sound, crashes on new world with modified music

### ISSUE THREAD

**Issue by Empour** [Vazkii/Ambience#4]
I spent a few hours picking out a lot of nice songs from Mystery Dungeon to put in the game using this, but when I tried to use it on my main instance, it didn't make any sound at all. 
When I made a new instance, with only Ambience, my custom sounds, and forge, it did not make the sound it was supposed to on the title screen, then it crashed upon loading into a new world(plains biome was seen before it crashed). 

FML Log: http://puu.sh/lt9ew/568a1e9c5e.log

My config and music folder: https://www.dropbox.com/s/4mp9450ekqgdteu/ambience_music.zip?dl=0

**Comment by Vazkii** [comment]
I can't reproduce it after fixing #2, so I must assume it's caused by #2, which is fixed.

On a side note, this pack rocks, if you're not putting it on curseforge I'm totally doing it for you :P

**Comment by Vazkii** [comment]
Here, you can even have an icon
![635836365244817502](https://cloud.githubusercontent.com/assets/1794735/11318820/463c7dca-9059-11e5-8c3a-660edd940476.png)
