### ISSUE TITLE
null.mp3 file not found when music muted

### ISSUE THREAD

**Issue by ewsmith** [Vazkii/Ambience#5]
when i mute the music to listen for creepers (yea, i know :c) the mod fails to find a null.mp3 file in the ambience_music/music folder and stops playing until i restart minecraft.
if i make an empty file for it the mod or minecraft deletes it.  setting the file to read only solves that.

[pastebin log snippit](http://pastebin.com/L2U9GW1r)

**Comment by WesCook** [comment]
This bug appears to still be in the mod.  Setting the volume to 0 creates log spam where it reports it's unable to find null.mp3.  The constant disk access may be having a performance impact, as well.

```
[05:45:39] [Ambience Player Thread/ERROR] [FML]: File <snip>\ambience_music\music\null.mp3 not found. Fix your Ambience config!
```

**Comment by ewsmith** [comment]
are you using linux? i never got the bug again after moving back to windows.

**Comment by WesCook** [comment]
Nope, I'm on Windows 10.
