### ISSUE TITLE
Musics from Ambience overlapping with Vanilla Music

### ISSUE THREAD

**Issue by Xen1290** [Vazkii/Ambience#6]
I think that vanilla music can be disabled when Ambience music play.
@Vazkii 
Sorry for possible english mistakes.

**Comment by ewsmith** [comment]
i made a resource pack that disables the vanilla music
https://drive.google.com/file/d/0B-QpwBSuVc6PTDFnOVltZWtwenc/view
just click the download button at the top

**Comment by Xen1290** [comment]
Thanks!

**Comment by OggeTheGamer** [comment]
@Vazkii I have the same problem today for 1.7.10
im using Ambience 1.0.3.jar, i would love if you could fix it

OTG
